language: node_js
sudo: false
node_js:
  - 10
install:
  - npm install
script:
  - npm run deploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  committer-from-gh: true
  on:
    branch: master